language: node_js

# Test against these versions of Node.js and io.js
node_js:
  - "stable"    # Node stable
  - "iojs"      # io.js latest
  - "unstable"  # Node unstable
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs-v1"

matrix:
  allow_failures:
    - node_js: "unstable"  # Node unstable
    - node_js: "iojs"      # io.js latest

install:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Node 0.8 comes with a too obsolete npm
  - if [[ "`node --version`" =~ ^v0\.8\. ]]; then npm install -g npm@1.4.28 ; fi
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
